services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
